enableGlobalCache: false

nodeLinker: pnp

# pnpMode: 'loose'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
packageExtensions:
  '@chakra-ui/utils@*':
    dependencies:
      'react': '*'
  '@types/node@*':
    peerDependencies:
      typescript: '*'
