enableGlobalCache: false

nodeLinker: pnp
# nodeLinker: node-modules

# pnpMode: 'loose'

yarnPath: .yarn/releases/yarn-4.5.0.cjs
packageExtensions:
  '@chakra-ui/utils@*':
    dependencies:
      react: '*'
  '@module-federation/nextjs-mf@*':
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  'next@*':
    dependencies:
      webpack: '*'
